CREATE OR REPLACE PROCEDURE <nombre procedimiento>(<parametros>)
IS
  <declaracion de variables>
BEGIN
  <instrucciones sql>
END;

DECLARACION DE PARAMETROS
<nombre parametro> IN|OUT|INT OUT<tipo de dato>
EJEMPLO
NOMBRE VARCHAR2

---CREAR UN SP(STORED PROCEDURE) OBTENER EL NOMBRE DE LAS CATEGORIAS E IMPRIMIR EL VALOR OBTENIDO, EL NOMBRE
---SE DEBE OBTENER DE LA CATEGORIA=2
CREATE OR REPLACE PROCEDURE SP_OBTENER_NOMB_CAT(IDCAT IN NUMBER)
IS
  NOMBRE_CAT CATEGORIES.CATEGORY_NAME%TYPE;
BEGIN
  SELECT CATEGORIES.CATEGORY_NAME INTO NOMBRE_CAT FROM CATEGORIES WHERE CATEGORY_ID=IDCAT;
  DBMS_OUTPUT.PUT_LINE('EL NOMBRE DE LA CATEGORIA ES:'||NOMBRE_CAT);
END;

EXECUTE SP_OBTENER_NOMB_CAT(2);

BEGIN 
  SP_OBTENER_NOMB_CAT(2);
END;



---CREAR UN SP QUE OBTENGA LA CANTIDAD TOTAL DE PRODUCTOS
CREATE OR REPLACEE PROCEDURE SP_CANT_PRODUCTOS
IS
  CANTIDAD NUMBER;
BEGIN
  SELECT COUNT(*) INTO CANTIDAD FROM PRODUCTS;
  DBMS_OUTPUT.PUT_LINE('LA CANTIDAD DE LOS PRODUCTOS GUARDADOS ES:'||CANTIDAD);
END;

---INSERTAR 
CREATE OR REPLACE PROCEDURE SP_INSERT_PRODUCTS(NOMB_PROD VARCHAR2, ID_BRAND NUMBER, CAT_ID NUMBER,
ANIO_MODELO NUMBER, PRECIO NUMBER, MSJ_ERROR OUT VARCHAR2, MSJ_EXITO OUT VARCHAR2)
IS
  
BEGIN
  
  
  INSERT INTO PRODUCTS (PRODUCT_NAME,BRAND_ID,CATEGORY_ID, MODEL_YEAR, LIST_PRICE) VALUES (NOMB_PROD,ID_BRAND,CAT_ID,ANIO_MODELO,PRECIO);
  COMMIT;
  
  MSJ_EXITO:='LA INSERCION DEL PRODUCTO FUE EXITOSA';
  
  EXCEPTION 
    WHEN OTHERS THEN
      MSJ_ERROR:=SQLERRM;
END;

CREATE SEQUENCE SQ_PRODUCTS
START WITH 323
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TG_SQ_PRODUCTS
BEFORE INSERT ON PRODUCTS
FOR EACH ROW
DECLARE

BEGIN
  :NEW.PRODUCT_ID:=SQ_PRODUCTS.NEXTVAL;
END;

-------------------------------------------------------------------

CREATE OR REPLACE PROCEDURE SP_INSERT_PRODUCTS(NOMB_PROD VARCHAR2, ID_BRAND NUMBER, CAT_ID NUMBER,
ANIO_MODELO NUMBER, PRECIO NUMBER, MSJ_ERROR OUT VARCHAR2, MSJ_EXITO OUT VARCHAR2)
IS
  CANTIDAD_REGISTROS NUMBER;
BEGIN
  
  SELECT COUNT(*) INTO CANTIDAD_REGISTROS FROM BRANDS WHERE BRAND_ID-ID_BRAND;
  IF (CANTIDAD_REGISTROS=1) THEN
    INSERT INTO PRODUCTS (PRODUCT_NAME,BRAND_ID,CATEGORY_ID, MODEL_YEAR, LIST_PRICE) VALUES (NOMB_PROD,ID_BRAND,CAT_ID,ANIO_MODELO,PRECIO);
    COMMIT;
  
  MSJ_EXITO:='LA INSERCION DEL PRODUCTO FUE EXITOSA';
  
  EXCEPTION 
    WHEN OTHERS THEN
      MSJ_ERROR:=SQLERRM;
END;

CREATE OR REPLACE 
